//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esqueletoProgramaCRUDconBD.D_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnicos
    {
        public int Id { get; set; }
        public int TrabajadorDTecnicoId { get; set; }
        public int JefeEquipoId { get; set; }
    
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual TrabajadoresDTecnico TrabajadoresDTecnico { get; set; }
    }
}
