//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esqueletoProgramaCRUDconBD.D_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadoresDTecnico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrabajadoresDTecnico()
        {
            this.JefesEquipo = new HashSet<JefesEquipo>();
            this.Tecnicos = new HashSet<Tecnicos>();
        }
    
        public int Id { get; set; }
        public int TrabajadorId { get; set; }
        public int AnyosExperiencia { get; set; }
        public string Tecnologia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JefesEquipo> JefesEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tecnicos> Tecnicos { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
