//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonGestionTrabajadoresMVC.Scripts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        public int Id { get; set; }
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public bool Borrado { get; set; }
    
        public virtual TrabajadoresDTecnico TrabajadoresDTecnico { get; set; }
    }
}
