//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiónEmpleados.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnicos
    {
        public int Id { get; set; }
        public int IdDT { get; set; }
        public int IdJefeEquipo { get; set; }
    
        public virtual JefeEquipos JefeEquipos { get; set; }
        public virtual TrabajoresDT TrabajoresDT { get; set; }
    }
}
